### ISSUE TITLE
For some reason the title References is duplicated in the pdf version

### ISSUE THREAD

**Issue by aito123** [quarto-journals/article-format-template#7]
Hello, thanks for creating this template.

I've seen that when rendering `aft-html: default` there is no problem with the Reference part. But when using `aft-pdf` at the end the title References appears double. You can see it in the demo pdf that you've published:

https://quarto-journals.github.io/article-format-template/

Is this a bug? Let me know.
Thanks

**Comment by cderv** [comment]
Thanks for the report. I removed from the template as the PDF version uses Natbib which already includes a title.
